<!-- Copyright © Erickson Lopez. MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EricksonLopez.Transaction.IntegrationTests</RootNamespace>
    <AssemblyName>EricksonLopez.Transaction.IntegrationTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Transaction.Abstractions\EricksonLopez.Transaction.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Transaction\EricksonLopez.Transaction.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Transaction.Dapper\EricksonLopez.Transaction.Dapper.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Transaction.PostgreSql\EricksonLopez.Transaction.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Transaction.Result\EricksonLopez.Transaction.Result.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Transaction.Testing\EricksonLopez.Transaction.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

</Project>
